name: Update Changelog

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: main

      - uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          header: |
            # Changelog

            All notable changes to this project are documented in this file. It is
            generated automatically from [GitHub Releases](../../releases) whenever a
            release is published.
